apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-webapp
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: webapp
        image: 675021605538.dkr.ecr.ap-south-1.amazonaws.com/devops-project:latest
        ports:
        - containerPort: 5000
